### ISSUE TITLE
Fix regex to allow testnet / devnet address balance lookup

### ISSUE THREAD

**Issue by 0xtrossets** [lAmeR1/kaspa-rest-server#35]
Currently, there's a hard input validation on addresses which only allows mainnet address balance to be looked up. Please remove or fix that regex so non-mainnet addresses can also be looked up.

**Comment by lAmeR1** [comment]
There is a Testnet branch, follow this

0xtrossets ***@***.***> schrieb am Di., 30. Apr. 2024, 02:42:

**Comment by lAmeR1** [comment]
There is a Testnet branch, check this please.

**Comment by 0xtrossets** [comment]
I'm using devnet though.
Can we please make the regex allow for non-mainnet addresses?

**Comment by 0xtrossets** [comment]
Same thing applies to other endpoints with the same regex validation
examples:
https://github.com/lAmeR1/kaspa-rest-server/blob/main/endpoints/get_balance.py#L18
https://github.com/lAmeR1/kaspa-rest-server/blob/main/endpoints/get_address_transactions.py#L51

**Comment by lAmeR1** [comment]
Hi,
I have a branch which you can use for testnet. I can merge it very soon, so you can set the env var to IS_TESTNET = true

I've used testnet branch and created a better solution in testnet_env_var

**Comment by 0xtrossets** [comment]
hi @lAmeR1 
this fix still only works for mainnet and testnet addresses.
What about simnet and devnet?
